sudo: required
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - g++ presentation.cpp -o mybinary
  
test:
  script:
    - ls -al
    - chmod +x runTests.sh
    - ./runTests.sh

